#%RAML 0.8

title: Player Service for RESTopoly
baseUri: http://example.api.com/player
version: v1
#traits:
#  - paged:
#      queryParameters:
#        pages:
#          description: The number of pages to return
#          type: number
#  - secured: !include http://remote-host/secured.yml


player/{gameId}:
  queryParameters:
    gameId:
      description: Id for the regarding game
  post:
    desciption: Creates a player for the given Game
    responses:
      201:
        body:
          application/json:
            schema: player
            example: |
              { "name": "Marcus",
                "uri": "Foo",
                "place": 1,
                "position": 1,
                "ready": true }
      409:
        body:
          application/json:
            schema: null
            example: |
              { null }

  /{playerId}:
    queryParameters:
      playderId:
        description: Id for the regarding player
    get:
      responses:
        200:
          body:
            application/json:
              schema: player
              example: |
                { "name": "Marcus",
                  "uri": "Foo",
                  "place": 1,
                  "position": 1,
                  "ready": true }
        404:
          body
            application/json:
              schema: null
              example: |
                { null }
    put:
      #TODO
